
create database MUZEJ;
use MUZEJ

create table IZLOZBA(
ID_IZLOZBE int NOT NULL PRIMARY KEY,
ID_DJELA int FOREIGN KEY REFERENCES DJELA(ID_DJELA),
NAZIV varchar(100)
);

create table DJELA(
ID_DJELA int NOT NULL PRIMARY KEY,
NAZIV varchar(100),
IME_UMJETNIKA varchar(50),
VRSTA_TEHNIKE varchar(50)
);


create table KUSTOS(
ID_KUSTOSA int NOT NULL PRIMARY KEY,
ID_IZLOZBE int FOREIGN KEY REFERENCES IZLOZBA(ID_IZLOZBE),
IME varchar(50),
PREZIME varchar(50)
);

create table SPONZOR(
ID_SPONZORA int NOT NULL PRIMARY KEY,
ID_IZLOZBE int FOREIGN KEY REFERENCES IZLOZBA(ID_IZLOZBE),
IME varchar(100),
ADRESA varchar(100)
);

create table MUZEJ(
ID_MUZEJA int NOT NULL PRIMARY KEY,
NAZIV varchar(50),
ADRESA varchar(100),
ID_IZLOZBE int FOREIGN KEY REFERENCES IZLOZBA(ID_IZLOZBE),
ID_DJELA int FOREIGN KEY REFERENCES DJELA(ID_DJELA),
ID_KUSTOSA int FOREIGN KEY REFERENCES KUSTOS(ID_KUSTOSA)
);

