create database SALON;
use SALON
create table DJELATNIK(
ID_DJELATNIKA int NOT NULL PRIMARY KEY,
IME varchar(50),
PREZIME varchar(50),
ADRESA varchar(100)
);

create table USLUGA(
ID_USLUGE int NOT NULL PRIMARY KEY,
NAZIV varchar(100),
CIJENA int
);


create table KORISNIK(
ID_KORISNIKA int NOT NULL IDENTITY(1,1) PRIMARY KEY,
IME varchar(50),
PREZIME varchar(50),
ADRESA varchar(50)
);

create table SALON_ZA_ULJEPSAVANJE(
ID_SALON_ZA_ULJEPSAVANJE int NOT NULL PRIMARY KEY,
NAZIV varchar(50),
ID_DJELATNIKA int FOREIGN KEY REFERENCES DJELATNIK(ID_DJELATNIKA),
ID_KORISNIKA int FOREIGN KEY REFERENCES KORISNIK(ID_KORISNIKA),
ID_USLUGE int FOREIGN KEY REFERENCES USLUGA(ID_USLUGE),
ADRESA varchar(100)
);