
create database SAMOSTAN;
use SAMOSTAN

create table SVECENIK(
ID_SVECENIKA int NOT NULL PRIMARY KEY,
IME varchar(50),
SV_IME varchar(60),
ID_POSLA int FOREIGN KEY REFERENCES POSAO(ID_POSLA),
ID_NADREDENOG int FOREIGN KEY REFERENCES NADREDENI_SVECENIK(ID_NADREDENOG)
);

create table POSAO(
ID_POSLA int NOT NULL PRIMARY KEY,
NAZIV varchar(100),
);


create table NADREDENI_SVECENIK(
ID_NADREDENOG int NOT NULL PRIMARY KEY,
IME varchar(50),
SV_IME varchar(60)
);

create table SAMOSTAN(
ID_SAMOSTANA int NOT NULL PRIMARY KEY,
NAZIV varchar(50),
ADRESA varchar(100),
ID_SVECENIKA int FOREIGN KEY REFERENCES SVECENIK(ID_SVECENIKA),
ID_NADREDENOG int FOREIGN KEY REFERENCES NADREDENI_SVECENIK(ID_NADREDENOG)
);

