
create database taksi;
use taksi

create table VOZILO(
ID_VOZILA int NOT NULL PRIMARY KEY,
MARKA varchar(100),
REG_TABLICU int
);

create table VOZAC(
ID_VOZACA int NOT NULL PRIMARY KEY,
ID_VOZILA int FOREIGN KEY REFERENCES VOZILO(ID_VOZILA),
IME varchar(100),
PREZIME varchar(50),
EMAIL varchar(50),
BR_MOBITELA int
);

create table VOZNJA(
ID_VOZNJA int NOT NULL PRIMARY KEY,
ID_VOZACA int FOREIGN KEY REFERENCES VOZAC(ID_VOZACA),
ID_PUTNIKA int FOREIGN KEY REFERENCES PUTNIK(ID_PUTNIKA),
CIJENA decimal
);


create table PUTNIK(
ID_PUTNIKA int NOT NULL PRIMARY KEY,
IME varchar(50),
PREZIME varchar(60),
EMAIL varchar(50),
BR_MOBITELA int
);

create table TAKSI_SLUZBA(
ID_TAKSI int NOT NULL PRIMARY KEY,
NAZIV varchar(50),
KONTAKT int,
ID_VOZILA int FOREIGN KEY REFERENCES VOZILO(ID_VOZILA),
ID_VOZACA int FOREIGN KEY REFERENCES VOZAC(ID_VOZACA),
ID_PUTNIKA int FOREIGN KEY REFERENCES PUTNIK(ID_PUTNIKA)
);

